/**
 * Generates seed.sql, which is applied with:
 *   wrangler d1 execute till-db --local --file=./seed.sql
 *
 * Runs under Node (`npm run seed:gen`) but reuses the Worker's PBKDF2 helpers,
 * so seeded PINs verify with exactly the same code path as live logins.
 */
import { writeFileSync } from "node:fs";
import { hashPin } from "./lib/crypto";
import { ulid } from "./lib/ids";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;

interface SeedUser {
  username: string;
  pin: string;
  role: "admin" | "cashier";
}

const SEED_USERS: SeedUser[] = [
  { username: "admin", pin: "1234", role: "admin" },
  { username: "cashier", pin: "4321", role: "cashier" },
];

async function main(): Promise<void> {
  const now = Date.now();
  const lines: string[] = [
    "-- Generated by `npm run seed:gen`. Do not edit by hand.",
    "PRAGMA defer_foreign_keys = true;",
    "DELETE FROM stock_movements;",
    "DELETE FROM payments;",
    "DELETE FROM sale_items;",
    "DELETE FROM sales;",
    "DELETE FROM products;",
    "DELETE FROM categories;",
    "DELETE FROM sessions;",
    "DELETE FROM users;",
  ];

  for (const u of SEED_USERS) {
    const { hash, salt } = await hashPin(u.pin);
    lines.push(
      `INSERT INTO users (id, username, pin_hash, pin_salt, role, active, created_at) VALUES (${q(
        ulid(),
      )}, ${q(u.username)}, ${q(hash)}, ${q(salt)}, ${q(u.role)}, 1, ${now});`,
    );
  }

  writeFileSync("seed.sql", `${lines.join("\n")}\n`, "utf8");
  console.log(`Wrote seed.sql with ${SEED_USERS.length} users.`);
  for (const u of SEED_USERS) console.log(`  ${u.role.padEnd(8)} ${u.username} / PIN ${u.pin}`);
}

void main();
